config:
  target: "http://localhost:31960"
  phases:
    - duration: 300
      arrivalRate: 10
      rampTo: 100

scenarios:
  - name: 'Trigger autoscaler'
    flow:
      - get: 
          url: "/"